### ISSUE TITLE
Any Release for NuGet Package?

### ISSUE THREAD

**Issue by enisn** [irensaltali/currency-dotnetcore#1]
Can you publish a release of binaries and push output to an artifact like NuGet?

**Comment by irensaltali** [comment]
There wasn't any release but I made quick publish after you open this issue. It isn't published yet. It may take a hour to start appear on search. I leave open this issue until it is successfully published.

Here is the link for it. 
https://www.nuget.org/packages/Irensaltali.Currency/0.1.0-beta

**Comment by irensaltali** [comment]
It is published.
`PM> Install-Package Irensaltali.Currency -Version 0.1.0-beta`
